services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent
    depends_on:
      - ollama
    environment:
      OLLAMA_URL: http://ollama:11434/api/generate
      MODEL: ${OLLAMA_MODEL:-deepseek-coder}  # Define the MODEL variable and default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: false

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama #Persist data between restarts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
