services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent
    environment:
      COMMAND: ${COMMAND}
      MAX_ATTEMPTS: ${MAX_ATTEMPTS:-3}
      MODEL: ${MODEL:-gemini}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      # Set MODEL to include "gemini" and provide GEMINI_API_KEY to use Gemini.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent/log:/app/data  # Bind-mount logs to the host directory
    privileged: false

volumes:
  ollama_data:  # This is not used anymore, remove this volume if you want
